## [Online Pandas Exercise](https://www.machinelearningplus.com/python/101-pandas-exercises-python/)
### 1.Create Series from dict /assign name

- pandas.Series(data=None, **index**=None, dtype=None, **name**=None, copy=False)
- pandas.DataFrame(data=None, **index**=None, **columns**=None, dtype=None, copy=False)

In [2]:
import numpy as np
import pandas as pd

In [3]:
# input
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

In [5]:
# output1
pd.Series(mydict).head()

a    0
b    1
c    2
d    4
e    3
dtype: int64

In [23]:
# output2
pd.Series(myarr, index=mylist, name='order').head()

a    0
b    1
c    2
e    3
d    4
Name: order, dtype: int64

### 2.convert the index of a sries into a column of a df

DataFrame.reset_index(level=None, **drop**=False, inplace=False, col_level=0, col_fill='')

In [9]:
# input
ser = pd.Series(mydict)

In [13]:
# output
ser.reset_index().head()

index  0
0     a  0
1     b  1
2     c  2
3     d  4
4     e  3

### 3.combine series to form df
- pandas.concat(objs(seq), **axis=0**, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False, sort=None, copy=True)
    -  axis: ({0/’index’, 1/’columns’}, default 0)
        - if two data frames have identical columns: append in rows
        - if two data frames have overlapping columns, concat in columns, with join set to be 'outer' or 'inner'. If 'outer', columns outside the intersection will be filled with NaN values.
    
- DataFrame.append(other, ignore_index=False, verify_integrity=False, sort=None)

In [14]:
# input
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)

In [15]:
# output1
pd.DataFrame({'col1': ser1, 'col2': ser2}).head()

col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4

In [16]:
# output2
pd.concat([ser1, ser2], axis=1).head()

0  1
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4

In [95]:
### axis=0: stack by row, same as append
assert pd.concat([ser1, ser2], axis=0).equals(ser1.append(ser2))

- keys : sequence, default None
    - If multiple levels passed, should contain tuples. Construct hierarchical index using the passed keys as the outermost level

In [35]:
pd.concat([ser1, ser2], keys=['s1', 's2'])

s1  0    1
    1    2
    2    3
    3    4
    4    5
s2  0    4
    1    5
    2    6
    3    7
    4    8
dtype: int64

### 4. get the items of series A not present in series B

In [24]:
# input 
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

In [25]:
# output
ser1[~ser1.isin(ser2)]

0    1
1    2
2    3
dtype: int64

### 5. get the items not common to both series A and series B

In [26]:
# output
ser1[~ser1.isin(ser2)].append(ser2[~ser2.isin(ser1)])

0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64

### 5. get the minimum, 25th percentile, median, 75th, and maximum
numpy.percentile(a, **q**, axis=None)
-  q: (float in range of [0,100] (or sequence of floats))

In [27]:
# input
np.random.RandomState(100)
ser_rand = pd.Series(np.random.normal(10, 5, 25))

In [29]:
# output
ser_rand.describe()

count    25.000000
mean      9.077290
std       4.287819
min       0.293734
25%       5.765617
50%       9.642595
75%      12.311676
max      16.386937
dtype: float64

In [30]:
np.percentile(ser_rand, q=[0, 25, 50, 75, 100])

array([  0.29373368,   5.76561679,   9.64259454,  12.31167644,  16.38693701])

### 6.get frequency counts of unique items of a series
- numpy.random.randint(low, high=None, size=None, dtype='l')
    - size : int or tuple of ints, optional (output shape)
- numpy.take(a, indices)
    - indices could be multi-dimensional
- numpy.random.choice(a, size=None, replace=True, p=None)
    - a: int or array
    - p: probability
- Series.value_counts(normalize=False, sort=True, ascending=False, bins=None, dropna=True)
    - bins: Rather than count values, group them into half-open bins, a convenience for pd.cut, only works with numeric data

In [32]:
# input
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

#output
ser.value_counts()

e    6
a    6
c    5
h    4
b    4
d    3
f    1
g    1
dtype: int64

In [91]:
ser2 = pd.Series(np.random.choice(10, 30))
ser2.value_counts(bins = [0, 3, 6, 10], normalize=True)

(-0.001, 3.0]    0.433333
(6.0, 10.0]      0.400000
(3.0, 6.0]       0.166667
dtype: float64

In [92]:
pd.cut(ser2, [-0.1, 3, 6, 10]).value_counts(normalize=True)

(-0.1, 3.0]    0.433333
(6.0, 10.0]    0.400000
(3.0, 6.0]     0.166667
dtype: float64

### 7. keep top 2 and replace others as 'other'

In [46]:
# input
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

In [47]:
ser[~ser.isin(ser.value_counts().index[:2])] = 'other'

In [48]:
ser

0         1
1         4
2     other
3         4
4     other
5         4
6     other
7     other
8         1
9         1
10    other
11        1
dtype: object

### 8. bin a numeric series to 10 groups of equal size?
- pandas.qcut(x, q, labels=None, retbins=False, precision=3)
Quantile-based discretization function. Discretize variable into equal-sized buckets based on rank or based on sample quantiles. For example 1000 values for 10 quantiles would produce a Categorical object indicating quantile membership for each data point.

In [49]:
# input
ser = pd.Series(np.random.random(20))

In [68]:
# pd.qcut(ser, q = np.linspace(0,1,11), 
#         labels=[str(i)+'th' if i > 3 
#                 else str(i) + 'rd' if i == 3 
#                 else str(i) + 'nd' if i == 2
#                 else str(i) + 'st' 
#                 for i in range(1, 11)])
pd.qcut(ser, q = np.linspace(0,1,11), 
        labels=['1st', '2nd', '3rd']+[str(i) + 'th' for i in range(4, 11)])

0      1st
1      1st
2      7th
3      4th
4      8th
5      6th
6      6th
7      4th
8      2nd
9      5th
10     9th
11     5th
12     3rd
13     8th
14     2nd
15     9th
16    10th
17     3rd
18    10th
19     7th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]

### 9.convert a series to df of given shape
- Series.values: Return Series as ndarray or ndarray-like depending on the dtype

In [77]:
# input 
ser = pd.Series(np.random.randint(1, 10, 35))
# output 
pd.DataFrame(ser.values.reshape(7,5))

0  1  2  3  4
0  8  4  8  8  6
1  4  8  5  6  9
2  7  8  7  7  7
3  4  9  6  9  5
4  4  9  2  5  7
5  3  5  4  1  2
6  5  5  9  7  6

### 10. find the positions of numbers that are multiples of 3 from a series
- np.argwhere(a): return non-zero index

~~~
>>> x = np.arange(6).reshape(2,3)

>>> x

array([[0, 1, 2],
       [3, 4, 5]])
       
>>> np.argwhere(x>1)

array([[0, 2],
       [1, 0],
       [1, 1],
       [1, 2]])
~~~

- np.where(condition, x, y): Return elements, either from x or y, depending on condition.
    - when x, y not given it works same as np.argwhere()
~~~
[xv if c else yv for (c,xv,yv) in zip(condition,x,y)]
~~~

In [113]:
# input
ser = pd.Series(np.random.randint(1, 10, 7))
print(ser)

0    7
1    7
2    6
3    3
4    2
5    3
6    9
dtype: int64


In [114]:
# output
ser[ser%3==0].index

Int64Index([2, 3, 5, 6], dtype='int64')

In [115]:
# output2
np.argwhere(ser%3==0)

array([[2],
       [3],
       [5],
       [6]])

In [118]:
np.where(ser%3==0)

(array([2, 3, 5, 6]),)

In [121]:
np.where(ser%3==0, np.ones(7), np.zeros(7))

array([ 0.,  0.,  1.,  1.,  0.,  1.,  1.])

### 11.extract at given positions
Series.take(indices, axis=0, convert=None, is_copy=True):
Return the elements in the given **positional** indices along an axis.

In [80]:
# Input
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

# Solution
ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [83]:
ser.iloc[pos]

0     a
4     e
8     i
14    o
20    u
dtype: object

### 12. get the positions of items of series A in another series B?
- Index.get_loc(key, method=None, tolerance=None)
    - return: **int** if unique index, **slice** if monotonic index, else **mask**

In [98]:
# Input
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
# output
ser1[ser1.isin(ser2)].index

Int64Index([0, 4, 5, 8], dtype='int64')

In [126]:
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

### 13.convert the first character of each element in a seris to uppercase
- str[0], str.get(0)
- str.lower()
- str.upper()
- str.title()
- str.len()
- str.strip(), str.lstrip(), str.rstrip()
- str.split()
    - string to list
    - expand = True, return a data frame with multi-columns
    - n, limit the number of splits
- str.replace()
    - regular expressions: '^.a|dog'
    - case: if case sensitive

In [139]:
# Input
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
# output
ser.str.title()

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [140]:
# output2
ser.apply(lambda x: x.title())

0     How
1      To
2    Kick
3    Ass?
dtype: object

In [131]:
ser.str.replace('o', 't')

0     htw
1      tt
2    kick
3    ass?
dtype: object

In [133]:
ser.str.get(0)

0    h
1    t
2    k
3    a
dtype: object

In [142]:
ser.str.len()

0    3
1    2
2    4
3    4
dtype: int64

### 14.compute difference of differences btw consequtive numbers of a series

In [143]:
#input
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

#output
ser.diff()

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64

In [145]:
ser.diff().diff().tolist()

[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]

### 15.convert date-strings to a timeseries

**Pandas time sereis classes**:
- Timestamp:
    - to_datetime: apply on integer, float, string, datetime, list, tuple, 1-d array, Series. 
        - format: '%Y-%b-%d'
        - 
    - Timestamp: apply on datetime-like, str, int, float
- DatetimeIndex:
    - pandas.date_range(start=None, end=None, periods=None, freq=None): return a fixed frequency datatime **index**
- Period:
    - Period
- PeriodIndex:
    - period_range, PeriodIndex
    
**Series.dt accessor**:
- year, quarter, month, week (in year), day (in month), dayofyear (in year), weekday (in week), weekday_name (in week), hour, second

**pandas.Timedelta**: represents a duration, the difference btween two dates or times

In [146]:
# input
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

# output
pd.to_datetime(ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

In [150]:
pd.Timestamp(ser[0])

Timestamp('2010-01-01 00:00:00')

In [148]:
pd.date_range('1/1/2011', periods=10, freq='H')

DatetimeIndex(['2011-01-01 00:00:00', '2011-01-01 01:00:00',
               '2011-01-01 02:00:00', '2011-01-01 03:00:00',
               '2011-01-01 04:00:00', '2011-01-01 05:00:00',
               '2011-01-01 06:00:00', '2011-01-01 07:00:00',
               '2011-01-01 08:00:00', '2011-01-01 09:00:00'],
              dtype='datetime64[ns]', freq='H')

In [153]:
pd.Period('2013-01-01', freq='M')

Period('2013-01', 'M')

In [176]:
pd.to_datetime(ser).dt.weekday_name

0       Friday
1    Wednesday
2     Saturday
3     Thursday
4       Monday
5     Saturday
dtype: object

In [177]:
pd.to_datetime(ser).diff().dt.days

0      NaN
1    397.0
2    395.0
3    397.0
4    396.0
5    397.0
dtype: float64

### 16. convert year-month string to dates corresponding to the 4th day of the month

In [178]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

In [182]:
pd.to_datetime(ser.apply(lambda x: '04 '+x))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

### 17.Filter words that contain at least 2 vowels from a series

- apply works on a row / column basis of a DataFrame
    - axis : {0 or ‘index’, 1 or ‘columns’}, default 0, Axis along which the function is applied:
        - 0 or ‘index’: apply function to each column.
        - 1 or ‘columns’: apply function to each row.
- applymap works element-wise on a DataFrame
- map works element-wise on a Series.

In [183]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

In [189]:
from collections import Counter
# apply also works
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in 'aeiou'])>=2)
ser[mask]

0     Apple
1    Orange
4     Money
dtype: object

### 18.filter valid emails from a series


In [188]:
# input 
mails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'

In [194]:
import re
mails[mails.map(lambda x: bool(re.match(pattern, x)))]

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object

In [199]:
mails.str.findall(pattern, flags=re.IGNORECASE)

0                     []
1    [rameses@egypt.com]
2            [matt@t.co]
3    [narendra@modi.com]
dtype: object

### 19. find all the local maxima in a numeric series

In [213]:
# input
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

# output
ser[np.sign(ser.diff()).diff()== -2].index-1

Int64Index([1, 5, 7], dtype='int64')

In [214]:
# output
np.where(np.sign(ser.diff()).diff()== -2)[0]-1

array([1, 5, 7])

### 20.replace missing space in a string with least frequent character

In [221]:
# input
my_str = 'dbc deb abed gadge'

# output
my_str.replace(' ', Counter(my_str).most_common()[-1][0])

'dbccdebcabedcgadge'

In [228]:
ser = pd.Series(list(my_str))
''.join(ser.replace(' ', ser.value_counts().index[-1]))

'dbccdebcabedcgadge'

### 21. create a time series starting from '2000-01-01' and 10 weekends, having random numbers as values.

In [236]:
pd.Series(np.random.randint(1,10,10), 
          index=pd.date_range('2000-01-01', periods=10, freq='W-SAT'))

2000-01-01    7
2000-01-08    9
2000-01-15    9
2000-01-22    9
2000-01-29    1
2000-02-05    4
2000-02-12    6
2000-02-19    8
2000-02-26    3
2000-03-04    4
Freq: W-SAT, dtype: int64

### 22.fill an intermittent time series with value from previous date

In [238]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64

In [243]:
ser.resample('D').ffill().ffill()

2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

### 23.compute the autocorrelations of a numeric series
Compute autocorrelations for the first 10 lags of ser. Find out which lag has the largest correlation.
- Series.autocorr(lag=1)

In [245]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

In [254]:
max(enumerate([ser.autocorr(i) for i in range(1, 11)]), key=lambda x: x[1])[0] + 1 

9

### 24.import only every nth row from a csv
- pandas.read_csv(filepath_or_buffer, sep=', ', delimiter=None, header='infer', names=None, index_col=None, usecols=None, squeeze=False, prefix=None, mangle_dupe_cols=True, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skipinitialspace=False, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, skip_blank_lines=True, parse_dates=False, infer_datetime_format=False, keep_date_col=False, date_parser=None, dayfirst=False, iterator=False, chunksize=None, compression='infer', thousands=None, decimal=b'.', lineterminator=None, quotechar='"', quoting=0, escapechar=None, comment=None, encoding=None, dialect=None, tupleize_cols=None, error_bad_lines=True, warn_bad_lines=True, skipfooter=0, doublequote=True, delim_whitespace=False, low_memory=True, memory_map=False, float_precision=None)
    - names: list of column names to use
    - **use_cols**: a subset of columns
    - header: int or list of ints: row number to use as column names
    - index_col: column to use as the row labels of df
    - prefix: prefix to add to column numbers when no header
    - dtype: type name or dict of column-> type
    - **converter**: dict of functions for converting values in certain columns
    - **skiprows**: 
        - list-like: line numbers to skip
        - int: number of lines to skip
        - callable: evaluated against the row indices, returning true if the row should be skipped and false otherwise. 
    - skipfooter: number of lines at bottom offile to skip
    - nrows: number of rows of file to read
    - na_values: additional strings to recognize as NA/NaN, if dict passed, specific per-column NA values
    - parse_dates:
        - boolean: true, parse the index
        - list of ints or names: parse as separate columns
        - list of lists: combine columns in list and parse as a single date column
        - dict: {'foo': [1,3]} -> parse columns 1,3 as date and call result 'foo'
    - chunksize: iterator
    
- DataFrame.to_csv(path_or_buf=None, sep=', ', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, mode='w', encoding=None, compression=None, quoting=None, quotechar='"', line_terminator='\n', chunksize=None, tupleize_cols=None, date_format=None, doublequote=True, escapechar=None, decimal='.')
    - columns: columns to write
    - header: Write out the column names. If a list of strings is given it is assumed to be aliases for the column names
    - index: index : boolean, default True, if write row names (index)
    - index_label : string or sequence, column label or labels for multi-index


In [255]:
df = pd.DataFrame({'col1': np.arange(50), 'col2': np.random.random(50)})
df.to_csv('sample.csv', index=False)

In [264]:
df.head()

col1      col2
0     0  0.607094
1     1  0.202053
2     2  0.039156
3     3  0.962819
4     4  0.661030

In [280]:
pd.read_csv('sample.csv', skiprows=lambda x: x%5!=0).head()

col1      col2
0     4  0.661030
1     9  0.132280
2    14  0.065755
3    19  0.893146
4    24  0.312014

### 25.change column values when import csv to a data frame
change to high if larger than 0.5 else low for col2 column

In [279]:
pd.read_csv('sample.csv', converters = {'col2': lambda x: 'high' if float(x)>0.5 else 'low'}).head()

col1  col2
0     0  high
1     1   low
2     2   low
3     3  high
4     4  high

### 26. import only specified columns

In [282]:
pd.read_csv('sample.csv', usecols=['col1']).head()

col1
0     0
1     1
2     2
3     3
4     4

### 27. rename column
- DataFrame.rename(mapper=None, index=None, columns=None, axis=None)

In [286]:
df.rename(columns={'col2':'random'}).head()

col1    random
0     0  0.607094
1     1  0.202053
2     2  0.039156
3     3  0.962819
4     4  0.661030

In [307]:
df.columns.values[1] = "random2"
df.head()

col1   random2
0     0  0.607094
1     1  0.202053
2     2  0.039156
3     3  0.962819
4     4  0.661030

### 28.Check if there is any missing vlaues or count missing value
- isnull()
- notnull()
- fillna(value=None, method=None, axis=None, inplace=False)
    - method : {‘backfill’, ‘bfill’, ‘pad’, ‘ffill’, None}, default None
- np.isnan()
- np.isfinite()
- dropna(axis=0, how='any', thresh=None, subset=None, inplace=False)
    - how: {'any', 'all'}
    - thresh: required number of non-NA values

In [292]:
df.isnull().values.any()

False

In [293]:
df.isnull().sum()

col1      0
random    0
dtype: int64

### 29.set number format 

In [317]:
# Input
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

In [318]:
df.round(4)

random
0  0.0000
1  0.0045
2  0.0391
3  0.0000

In [326]:
# dtype has changed from float to object
df.applymap(lambda x: '{:.4f}'.format(x))

random
0  0.0000
1  0.0045
2  0.0391
3  0.0000

In [331]:
df.applymap(lambda x: '{:.2%}'.format(x))

random
0  0.00%
1  0.45%
2  3.91%
3  0.00%

### 30. filter every nth row in df

In [332]:
df.iloc[::2, :]

random
0  1.408704e-16
2  3.910897e-02

### 31. get row number of the nth largest value in a column
- argsort: return the **indeces** that would sort an array
- rank: r

In [357]:
# Input
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
df.a

0    12
1    11
2     7
3    19
4    19
5    10
6    15
7    20
8    17
9    17
Name: a, dtype: int64

In [364]:
n=2
df.a.argsort()[::-1].tolist()[2]

3

In [359]:
df.a[df.a.argsort()]

a
2     7
5    10
1    11
0    12
6    15
8    17
9    17
3    19
4    19
7    20
Name: a, dtype: int64

### 32.get the last n rows of a df with row sums > 100

In [367]:
# Input
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [374]:
n = 3
df[df.sum(axis=1) > 100]

0   1   2   3
0   34  36  28  16
1   37  31  23  20
2   27  27  36  28
5   20  35  17  37
6   34  36  36  22
9   22  34  37  33
12  33  32  12  27
13  16  30  25  39

In [375]:
df[df.sum(axis=1) > 100].iloc[-2:,:]

0   1   2   3
12  33  32  12  27
13  16  30  25  39

### 33.find and cap outliers from a series
replace all values in the lower 5% by 5th percentile value, same for those greater than 95%
- numpy.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
- numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

In [378]:
# Input
ser = pd.Series(np.logspace(-2, 2, 30))
ser.head()

0    0.010000
1    0.013738
2    0.018874
3    0.025929
4    0.035622
dtype: float64

In [381]:
low, high = np.percentile(ser, q=[5, 95])
ser[ser<low] = low
ser[ser>high] = high
ser.head()

0    0.016049
1    0.016049
2    0.018874
3    0.025929
4    0.035622
dtype: float64

### 34. reshape df to the largest possible square after removing the negative values

In [391]:
# Input
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

In [408]:
arr = df.values.flatten()
arr = arr[arr>0]
n = int(np.floor(np.sqrt(arr.shape[0])))
pd.DataFrame(arr[:n**2].reshape((n, n)))

0   1   2   3   4   5   6   7
0  15  27   2  49  39  45   8   3
1  18  25  44   2  28  45   7  10
2  48  10  34  49   4   4  28   9
3  47  34  43  21  14  33   2   4
4  10  35  41  23  23  16  21  46
5  32  19  18   8  19  10  30  23
6  48   5  40  40  43  11  20  31
7   1   4  47   1  17   8  39   9

### 35.one-hot encoding of a categorical variable
- pandas.get_dummies(data, prefix=None, prefix\_sep='_', dummy_na=False, columns=None, sparse=False, drop_first=False, dtype=None)

In [411]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
df

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [414]:
pd.concat([pd.get_dummies(df.a, prefix='a', prefix_sep='_'), df.iloc[:, 1:]], axis=1)

a_0  a_5  a_10  a_15  a_20   b   c   d   e
0    1    0     0     0     0   1   2   3   4
1    0    1     0     0     0   6   7   8   9
2    0    0     1     0     0  11  12  13  14
3    0    0     0     1     0  16  17  18  19
4    0    0     0     0     1  21  22  23  24

### 36.which column contains the highest number of row-wise max values

In [417]:
# Input
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
df

0   1   2   3
0  12  32  27  93
1  81  92  47  90
2  89  68  55  49
3  98  51   5  56
4   9   9  12  21
5  54  17  28  19
6  29  24   3  18
7  87  39  25  17
8  38  42  16  29
9  10   8  12  55

In [422]:
# The column index which has the max in each row
df.apply(np.argmax, axis=1)

0    3
1    1
2    0
3    0
4    3
5    0
6    0
7    0
8    1
9    3
dtype: int64

In [424]:
df.apply(np.argmax, axis=1).value_counts().index[0]

0

### 37.create a new column that contains the row number of nearest column by euclidean distance?